<%@page contentType="text/html" pageEncoding="UTF-8"%><%@page import="java.util.List"%><%@page import="java.util.Map"%>
<%
String username=(String)session.getAttribute("username"),role=(String)session.getAttribute("role");if(username==null||!"Cashier".equalsIgnoreCase(role)){response.sendRedirect("login.jsp");return;}
List<Map<String,Object>> appointments=(List<Map<String,Object>>)request.getAttribute("appointments");Map<String,Object> bill=(Map<String,Object>)request.getAttribute("bill");String query=(String)request.getAttribute("query"),error=(String)request.getAttribute("error"),success=(String)request.getAttribute("success");
%>
<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"><title>Cashier Billing - Sunrise Dental Clinic</title>
<style>
*{box-sizing:border-box}body{margin:0}.navbar{display:flex;justify-content:space-between;align-items:center}.navbar a{color:white;text-decoration:none;font-weight:bold}.container{max-width:1200px;margin:40px auto;padding:0 20px}.box,.receipt{padding:30px;background:white;margin-bottom:24px}.search{display:grid;grid-template-columns:1fr auto;gap:10px}.search input{min-height:46px;padding:11px;border:1px solid #bfd3d3}.search button,.pay button,.print{min-height:44px;padding:0 20px;border:0;font-weight:bold;cursor:pointer}.message{padding:13px;margin:15px 0;border-radius:9px}.error{color:#9d2638;background:#ffeaed}.success{color:#176454;background:#e8f8f2}.table-wrap{margin-top:22px;overflow-x:auto;border:1px solid #dce9e8;border-radius:12px}table{width:100%;min-width:900px;border-collapse:collapse}th,td{padding:12px;text-align:left;border-bottom:1px solid #dce9e8}.status{padding:4px 9px;border-radius:999px;background:#fff5d8;font-weight:bold}.status.paid{color:#176454;background:#e8f8f2}.status.refunded{color:#9d2638;background:#ffeaed}.open{display:inline-flex;padding:8px 12px;color:white!important;background:#21a7a0;border-radius:8px;text-decoration:none;font-weight:bold}.receipt-head{text-align:center;padding-bottom:18px;border-bottom:2px solid #dce9e8}.receipt-head h2{margin:0}.payment-banner{margin:18px 0;padding:15px;text-align:center;border-radius:9px;font-weight:bold}.payment-banner.unpaid{color:#8a6100;background:#fff5d8}.payment-banner.paid{color:#176454;background:#e8f8f2}.payment-banner.refunded{color:#9d2638;background:#ffeaed}.details{display:grid;grid-template-columns:1fr 1fr;gap:0 25px}.row{display:flex;justify-content:space-between;gap:18px;padding:12px 0;border-bottom:1px solid #e6ebf1}.row strong:last-child{text-align:right}.costs{margin-top:20px;border:1px solid #dce9e8;border-radius:10px;overflow:hidden}.costs .row{padding:13px 16px}.total{color:white;background:#123047;font-size:20px}.pay{margin-top:20px;padding:18px;background:#f4fbf9;border-radius:10px}.pay form{display:flex;gap:10px}.pay select{flex:1;min-height:44px;padding:9px;border:1px solid #bfd3d3}.print{width:100%;margin-top:20px;color:white;background:#21a7a0}.back{display:block;text-align:center;text-decoration:none;font-weight:bold}@media(max-width:650px){.search,.details{grid-template-columns:1fr}.pay form{flex-direction:column}}@media print{.navbar,.box,.pay,.print,.back{display:none!important}.receipt{box-shadow:none;margin:0;padding:0}.container{margin:0;max-width:none}}
</style><link rel="stylesheet" href="${pageContext.request.contextPath}/css/clinic-theme.css"></head><body>
<header class="navbar"><strong>Sunrise Dental Clinic | Cashier</strong><a href="cashierDashboard.jsp">Dashboard</a></header><main class="container">
<section class="box"><h1>Search Appointments and Billing</h1><p>Search by appointment number, patient name or phone number. Searching never collects payment.</p>
<form class="search" action="${pageContext.request.contextPath}/BillServlet" method="get"><input type="search" name="query" value="<%=query==null?"":query%>" placeholder="Appointment number, patient name or phone"><button type="submit">Search</button></form>
<%if(error!=null){%><div class="message error"><%=error%></div><%}if(success!=null){%><div class="message success"><%=success%></div><%}%>
<div class="table-wrap"><table><thead><tr><th>Appointment</th><th>Patient</th><th>Phone</th><th>Date</th><th>Appointment Status</th><th>Payment</th><th>Action</th></tr></thead><tbody>
<%if(appointments!=null&&!appointments.isEmpty())for(Map<String,Object> item:appointments){String ps=String.valueOf(item.get("paymentStatus"));%><tr><td><%=item.get("appointmentNumber")%></td><td><%=item.get("patientName")%></td><td><%=item.get("contactNumber")%></td><td><%=item.get("appointmentDate")%> <%=item.get("appointmentTime")%></td><td><%=item.get("appointmentStatus")%></td><td><span class="status <%=ps.toLowerCase()%>"><%=ps%></span></td><td><a class="open" href="${pageContext.request.contextPath}/BillServlet?appointmentNumber=<%=item.get("appointmentNumber")%>&query=<%=query==null?"":java.net.URLEncoder.encode(query,java.nio.charset.StandardCharsets.UTF_8)%>"><%="Paid".equalsIgnoreCase(ps)?"Open Receipt":"Review"%></a></td></tr><%}else{%><tr><td colspan="7">No appointments found.</td></tr><%}%>
</tbody></table></div></section>
<%if(bill!=null){String ps=String.valueOf(bill.get("paymentStatus"));boolean paid="Paid".equalsIgnoreCase(ps),unpaid="Unpaid".equalsIgnoreCase(ps);%><section class="receipt"><div class="receipt-head"><h2>Sunrise Dental Clinic</h2><p>Cashier Payment Receipt</p></div><div class="payment-banner <%=ps.toLowerCase()%>">Payment Status: <%=ps%><%if(unpaid){%> — Collect payment before printing the official receipt.<%}%></div>
<div class="details"><div class="row"><strong>Appointment</strong><span><%=bill.get("appointmentNumber")%></span></div><div class="row"><strong>Patient</strong><span><%=bill.get("patientName")%></span></div><div class="row"><strong>Phone</strong><span><%=bill.get("contactNumber")%></span></div><div class="row"><strong>Dentist</strong><span><%=bill.get("dentistName")%></span></div><div class="row"><strong>Treatment</strong><span><%=bill.get("treatmentName")%></span></div><div class="row"><strong>Date / Time</strong><span><%=bill.get("appointmentDate")%> <%=bill.get("appointmentTime")%></span></div><%if(!unpaid){%><div class="row"><strong>Payment reference</strong><span><%=bill.get("paymentReference")%></span></div><div class="row"><strong>Payment method</strong><span><%=bill.get("paymentMethod")%><%=String.valueOf(bill.get("cardLastFour")).isEmpty()?"":" ending "+bill.get("cardLastFour")%></span></div><div class="row"><strong>Paid at</strong><span><%=bill.get("paymentDate")%></span></div><%if("Refunded".equalsIgnoreCase(ps)){%><div class="row"><strong>Refund reference</strong><span><%=bill.get("refundReference")%></span></div><div class="row"><strong>Refunded at</strong><span><%=bill.get("refundedAt")%></span></div><%}}%></div>
<div class="costs"><div class="row"><span>Treatment charge<br><small>Doctor and equipment charges included</small></span><strong>Rs. <%=bill.get("treatmentCost")%></strong></div><div class="row"><span>Hospital charges</span><strong>Rs. <%=bill.get("hospitalCharge")%></strong></div><div class="row total"><strong>Total <%="Refunded".equalsIgnoreCase(ps)?"Refunded":paid?"Paid":"Due"%></strong><strong>Rs. <%="Refunded".equalsIgnoreCase(ps)?bill.get("refundedAmount"):bill.get("totalAmount")%></strong></div></div>
<%if(unpaid&&!"Cancelled".equalsIgnoreCase(String.valueOf(bill.get("appointmentStatus")))&&!"Rejected".equalsIgnoreCase(String.valueOf(bill.get("appointmentStatus")))){%><div class="pay"><strong>Collect Counter Payment</strong><form action="${pageContext.request.contextPath}/BillServlet" method="post" onsubmit="return confirm('Confirm that full payment was collected?');"><input type="hidden" name="appointmentNumber" value="<%=bill.get("appointmentNumber")%>"><select name="paymentMethod" required><option value="">Select method</option><option>Cash</option><option>Card - Counter</option></select><button type="submit">Mark Paid</button></form></div><%}%>
<%if(paid||"Refunded".equalsIgnoreCase(ps)){%><button class="print" type="button" onclick="window.print()">Print <%=paid?"Receipt":"Refund Record"%></button><%}%></section><%}%>
<a class="back" href="cashierDashboard.jsp">← Back to Cashier Dashboard</a></main></body></html>
