<%@page contentType="text/html" pageEncoding="UTF-8"%><%@page import="java.util.Map"%>
<%
String username=(String)session.getAttribute("username"),role=(String)session.getAttribute("role");if(username==null||!"Cashier".equalsIgnoreCase(role)){response.sendRedirect("login.jsp");return;}
Map<String,Object> bill=(Map<String,Object>)request.getAttribute("bill");String error=(String)request.getAttribute("error"),success=(String)request.getAttribute("success");
%>
<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"><title>Payment and Receipt - Sunrise Dental Clinic</title>
<style>
*{box-sizing:border-box}body{margin:0}.navbar{display:flex;justify-content:space-between;align-items:center}.navbar a{color:white;text-decoration:none;font-weight:bold}.container{max-width:900px;margin:40px auto;padding:0 20px}.receipt{padding:32px;background:white}.receipt-head{text-align:center;padding-bottom:18px;border-bottom:2px solid #dce9e8}.receipt-head h1{margin:0}.message{padding:13px;margin:15px 0;border-radius:9px}.payment-banner{margin:18px 0;padding:15px;text-align:center;border-radius:9px;font-weight:bold}.payment-banner.unpaid{color:#8a6100;background:#fff5d8}.payment-banner.paid{color:#176454;background:#e8f8f2}.payment-banner.refunded{color:#9d2638;background:#ffeaed}.details{display:grid;grid-template-columns:1fr 1fr;gap:0 25px}.row{display:flex;justify-content:space-between;gap:18px;padding:12px 0;border-bottom:1px solid #e6ebf1}.row strong:last-child{text-align:right}.costs{margin-top:20px;border:1px solid #dce9e8;border-radius:10px;overflow:hidden}.costs .row{padding:13px 16px}.total{color:white;background:#123047;font-size:20px}.pay{margin-top:20px;padding:18px;background:#f4fbf9;border-radius:10px}.pay form{display:flex;gap:10px;margin-top:12px}.pay select{flex:1;min-height:44px;padding:9px;border:1px solid #bfd3d3}.pay button,.print{min-height:44px;padding:0 20px;border:0;font-weight:bold;cursor:pointer}.print{width:100%;margin-top:20px;color:white;background:#21a7a0}.back{display:block;margin-top:22px;text-align:center;text-decoration:none;font-weight:bold}@media(max-width:650px){.details{grid-template-columns:1fr}.pay form{flex-direction:column}}@media print{.navbar,.pay,.print,.back,.message{display:none!important}.receipt{box-shadow:none;margin:0;padding:0}.container{margin:0;max-width:none}}
</style><link rel="stylesheet" href="${pageContext.request.contextPath}/css/clinic-theme.css"></head><body>
<header class="navbar"><strong>Sunrise Dental Clinic | Cashier</strong><a href="cashierDashboard.jsp">Dashboard</a></header><main id="receipt-task" class="container ux-focus-target" tabindex="-1">
<%if(error!=null){%><div class="message error" role="alert"><%=error%></div><%}if(success!=null){%><div class="message success" role="status"><%=success%></div><%}%>
<%if(bill!=null){String ps=String.valueOf(bill.get("paymentStatus"));boolean paid="Paid".equalsIgnoreCase(ps),unpaid="Unpaid".equalsIgnoreCase(ps),refunded="Refunded".equalsIgnoreCase(ps);String appointmentStatus=String.valueOf(bill.get("appointmentStatus"));%>
<section class="receipt"><div class="receipt-head"><h1>Payment and Appointment Receipt</h1><p>Sunrise Dental Clinic</p></div><div class="payment-banner <%=ps.toLowerCase()%>">Payment Status: <%=ps%><%if(unpaid){%> — Collect payment before printing the official receipt.<%}%></div>
<div class="details"><div class="row"><strong>Appointment</strong><span><%=bill.get("appointmentNumber")%></span></div><div class="row"><strong>Patient</strong><span><%=bill.get("patientName")%></span></div><div class="row"><strong>Phone</strong><span><%=bill.get("contactNumber")%></span></div><div class="row"><strong>Dentist</strong><span><%=bill.get("dentistName")%></span></div><div class="row"><strong>Treatment</strong><span><%=bill.get("treatmentName")%></span></div><div class="row"><strong>Date / Time</strong><span><%=bill.get("appointmentDate")%> <%=bill.get("appointmentTime")%></span></div><div class="row"><strong>Appointment status</strong><span><%=appointmentStatus%></span></div>
<%if(!unpaid){%><div class="row"><strong>Payment reference</strong><span><%=bill.get("paymentReference")%></span></div><div class="row"><strong>Payment method</strong><span><%=bill.get("paymentMethod")%><%=String.valueOf(bill.get("cardLastFour")).isEmpty()?"":" ending "+bill.get("cardLastFour")%></span></div><div class="row"><strong>Paid at</strong><span><%=bill.get("paymentDate")%></span></div><%if(refunded){%><div class="row"><strong>Refund reference</strong><span><%=bill.get("refundReference")%></span></div><div class="row"><strong>Refunded at</strong><span><%=bill.get("refundedAt")%></span></div><%}}%></div>
<div class="costs"><div class="row"><span>Treatment charge<br><small>Doctor and equipment charges included</small></span><strong>Rs. <%=bill.get("treatmentCost")%></strong></div><div class="row"><span>Hospital charges</span><strong>Rs. <%=bill.get("hospitalCharge")%></strong></div><div class="row total"><strong>Total <%=refunded?"Refunded":paid?"Paid":"Due"%></strong><strong>Rs. <%=refunded?bill.get("refundedAmount"):bill.get("totalAmount")%></strong></div></div>
<%if(unpaid&&!"Cancelled".equalsIgnoreCase(appointmentStatus)&&!"Rejected".equalsIgnoreCase(appointmentStatus)){%><div class="pay"><strong>Collect Counter Payment</strong><p>Confirm the full amount has been received before marking this appointment as paid.</p><form action="${pageContext.request.contextPath}/CashierReceiptServlet" method="post" onsubmit="return confirm('Confirm that full payment was collected?');"><input type="hidden" name="appointmentNumber" value="<%=bill.get("appointmentNumber")%>"><select name="paymentMethod" required aria-label="Payment method"><option value="">Select payment method</option><option>Cash</option><option>Card - Counter</option></select><button type="submit">Mark Paid</button></form></div><%}%>
<%if(paid||refunded){%><button class="print" type="button" onclick="window.print()">Print <%=paid?"Receipt":"Refund Record"%></button><%}%></section><%}%>
<a class="back" href="${pageContext.request.contextPath}/BillServlet">← Back to Appointment Search</a></main><script src="${pageContext.request.contextPath}/js/clinic-ux.js"></script><script>window.addEventListener("DOMContentLoaded",function(){document.getElementById("receipt-task").focus({preventScroll:true});});</script></body></html>
