<%@page contentType="text/html" pageEncoding="UTF-8"%>
<%@page import="java.time.LocalDate"%><%@page import="java.util.List"%><%@page import="java.util.Map"%>
<%! private String v(Object value) { return value == null ? "" : String.valueOf(value); } %>
<%
String username=(String)session.getAttribute("username"),role=(String)session.getAttribute("role");
if(username==null||!("Admin".equalsIgnoreCase(role)||"Staff".equalsIgnoreCase(role))){response.sendRedirect("login.jsp");return;}
String error=(String)request.getAttribute("error"),success=(String)request.getAttribute("successMessage"),scheduleMessage=(String)request.getAttribute("scheduleMessage");
Integer selectedTreatmentId=(Integer)request.getAttribute("selectedTreatmentId"),selectedDentistId=(Integer)request.getAttribute("selectedDentistId");
LocalDate selectedDate=(LocalDate)request.getAttribute("selectedDate");
List<Map<String,Object>> treatments=(List<Map<String,Object>>)request.getAttribute("treatments"),dentists=(List<Map<String,Object>>)request.getAttribute("dentists");
List<Map<String,String>> slots=(List<Map<String,String>>)request.getAttribute("availableSlots");
String dashboard="Admin".equalsIgnoreCase(role)?"adminDashboard.jsp":"dashboard.jsp";
%>
<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"><title>Reserve Appointment - Sunrise Dental Clinic</title>
<style>
*{box-sizing:border-box}body{margin:0}.navbar{display:flex;justify-content:space-between;align-items:center}.navbar a{color:white;text-decoration:none;font-weight:bold}.container{max-width:920px;margin:38px auto;padding:0 20px}.box{padding:34px;background:white}h1{margin:0 0 7px;text-align:center}.subtitle{text-align:center;margin:0 0 25px}.steps{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin-bottom:26px}.step{padding:11px;color:#607583;background:#edf2f3;border-radius:8px;text-align:center;font-size:13px;font-weight:bold}.step.active{color:#176b87;background:#e9f8f5}.message,.notice{padding:13px;margin-bottom:18px;border-radius:9px}.error{color:#9d2638;background:#ffeaed}.success{color:#176454;background:#e8f8f2}.info{color:#775300;background:#fff5d8}.notice{color:#123047;background:#e9f8f5}.form-grid,.patient-grid{display:grid;grid-template-columns:1fr 1fr;gap:18px}.field.full,.full{grid-column:1/-1}.field label{display:block;margin-bottom:7px;color:#123047;font-weight:bold}.field select,.field input,.field textarea{width:100%;min-height:45px;padding:10px;border:1px solid #bfd3d3}.hint{margin:6px 0 0;color:#607583;font-size:13px}.button{width:100%;min-height:46px;margin-top:18px;border:0;font-weight:bold;cursor:pointer}.slots-panel,.patient-panel{margin-top:27px;padding-top:25px;border-top:1px solid #dce9e8}.slot-summary{color:#607583}.slots{display:grid;grid-template-columns:repeat(4,1fr);gap:10px}.slot{position:relative}.slot input{position:absolute;opacity:0}.slot span{display:block;padding:11px;border:1px solid #b9dcda;border-radius:8px;color:#176b87;text-align:center;font-weight:bold;cursor:pointer}.slot input:checked+span{color:white;background:#21a7a0}.empty{padding:18px;color:#607583;background:#f4fbf9;border-radius:9px;text-align:center}.back{display:block;margin-top:22px;text-align:center;text-decoration:none;font-weight:bold}@media(max-width:700px){.form-grid,.patient-grid{grid-template-columns:1fr}.field.full,.full{grid-column:auto}.slots{grid-template-columns:repeat(2,1fr)}.box{padding:23px 16px}}
</style><style>.date-grid{display:grid;grid-template-columns:repeat(5,1fr);gap:9px;max-height:250px;padding:4px;overflow-y:auto}.date-option{margin:0;position:relative}.date-option input{position:absolute;opacity:0;pointer-events:none}.date-option span{display:grid;gap:3px;min-height:62px;padding:9px 5px;align-content:center;border:1px solid #bfcde0;border-radius:8px;color:#176b87;background:white;text-align:center;cursor:pointer}.date-option input:checked+span{color:white;background:#21a7a0;border-color:#21a7a0}.calendar-empty{grid-column:1/-1;margin:0;padding:16px;color:#687687;background:#f5f7fa;text-align:center}@media(max-width:700px){.date-grid{grid-template-columns:repeat(3,1fr)}}</style><link rel="stylesheet" href="${pageContext.request.contextPath}/css/clinic-theme.css"></head><body>
<header class="navbar"><strong class="navbar-title">Sunrise Dental Clinic | <%=role%></strong><a href="<%=dashboard%>">Dashboard</a></header>
<main class="container"><section class="box"><h1>Reserve Phone / Walk-in Appointment</h1><p class="subtitle">Choose a treatment, dentist and live time slot. This reservation does not collect payment.</p>
<div class="steps"><div class="step active">1. Choose treatment</div><div class="step <%=selectedTreatmentId!=null?"active":""%>">2. Check availability</div><div class="step <%=slots!=null?"active":""%>">3. Choose slot</div></div>
<div class="notice"><strong>Payment status will be Unpaid.</strong> The cashier collects payment and prints the official receipt.</div>
<%if(error!=null){%><div class="message error" role="alert"><%=error%></div><%}if(success!=null){%><div class="message success" role="status"><%=success%></div><%}if(scheduleMessage!=null){%><div class="message info"><%=scheduleMessage%></div><%}%>

<form id="booking-options" class="ux-focus-target" action="${pageContext.request.contextPath}/AppointmentServlet" method="get" tabindex="-1"><div class="form-grid">
<div class="field <%=selectedTreatmentId==null?"full":""%>"><label for="treatmentId">Treatment</label><select id="treatmentId" name="treatmentId" required><option value="">Select treatment</option><%if(treatments!=null)for(Map<String,Object>t:treatments){Integer id=(Integer)t.get("id");%><option value="<%=id%>" <%=id.equals(selectedTreatmentId)?"selected":""%>><%=t.get("name")%> — <%=t.get("detail")%></option><%}%></select></div>
<%if(selectedTreatmentId!=null){%><div class="field"><label for="dentistId">Dentist</label><select id="dentistId" name="dentistId" required><option value="">Select dentist</option><%if(dentists!=null)for(Map<String,Object>d:dentists){Integer id=(Integer)d.get("dentistId");%><option value="<%=id%>" data-days="<%=d.get("availableDays")%>" data-leaves="<%=d.get("leaveDates")%>" <%=id.equals(selectedDentistId)?"selected":""%>><%=d.get("dentistName")%> — <%=d.get("availableDay")%></option><%}%></select><%if(dentists==null||dentists.isEmpty()){%><p class="hint">No dentist with configured visiting hours offers this treatment.</p><%}%></div>
<div class="field full"><label id="appointmentDateLabel">Available appointment dates</label><div id="appointment-calendar" class="date-grid ux-focus-target" tabindex="-1" aria-labelledby="appointmentDateLabel"></div><p class="hint">Only active visiting weekdays are shown. Announced leave dates are excluded.</p></div><%}%></div>
<button class="button" type="submit"><%=selectedTreatmentId==null?"Continue to Dentists":"Show Available Slots"%></button></form>

<%if(slots!=null&&scheduleMessage==null){%><section id="slot-options" class="slots-panel ux-focus-target" tabindex="-1"><h2>Available time slots</h2><p class="slot-summary"><%=request.getAttribute("selectedDentistName")%> · <%=selectedDate%> · <%=request.getAttribute("visitingWindow")%></p>
<%if(!slots.isEmpty()){%><form action="${pageContext.request.contextPath}/AppointmentServlet" method="post"><input type="hidden" name="treatmentId" value="<%=selectedTreatmentId%>"><input type="hidden" name="dentistId" value="<%=selectedDentistId%>"><input type="hidden" name="appointmentDate" value="<%=selectedDate%>"><div class="slots"><%for(Map<String,String>slot:slots){%><label class="slot"><input type="radio" name="appointmentTime" value="<%=slot.get("value")%>" required><span><%=slot.get("label")%></span></label><%}%></div>
<section class="patient-panel"><h2>Patient details</h2><div class="patient-grid"><div class="field"><label for="patientName">Patient Name</label><input id="patientName" name="patientName" value="<%=v(request.getAttribute("form_patientName"))%>" required></div><div class="field"><label for="contactNumber">Phone Number</label><input id="contactNumber" name="contactNumber" type="tel" pattern="[0-9]{10}" maxlength="10" value="<%=v(request.getAttribute("form_contactNumber"))%>" required></div><div class="field full"><label for="address">Address</label><textarea id="address" name="address" rows="3" required><%=v(request.getAttribute("form_address"))%></textarea></div></div></section><button class="button" type="submit">Reserve Without Payment</button></form>
<%}else{%><div class="empty">No slots remain for this date. Choose another dentist or date.</div><%}%></section><%}%>
<a class="back" href="<%=dashboard%>">← Back to Dashboard</a></section></main>
<script src="${pageContext.request.contextPath}/js/clinic-ux.js"></script><script src="${pageContext.request.contextPath}/js/booking-calendar.js"></script><script>initClinicBookingCalendar({dentistSelectId:"dentistId",calendarId:"appointment-calendar",selectedDate:"<%=selectedDate==null?"":selectedDate%>"});</script><%if(slots!=null){%><script>window.addEventListener("DOMContentLoaded",function(){clinicFocusSection("slot-options");});</script><%}else if(selectedTreatmentId!=null){%><script>window.addEventListener("DOMContentLoaded",function(){clinicFocusSection("booking-options");});</script><%}%>
</body></html>
